# Generated by Django 5.1.2 on 2025-03-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_category_expense_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='expense',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
