# Generated by Django 5.1.2 on 2025-03-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user_id',
        ),
    ]
