# Generated by Django 5.1.2 on 2025-03-22 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_remove_category_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
