# Generated by Django 5.1.2 on 2025-03-22 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_remove_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='budget',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='expense',
        ),
        migrations.DeleteModel(
            name='income',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
