# Generated by Django 5.1.2 on 2025-04-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0010_alter_income_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
