# Generated by Django 5.1.2 on 2025-04-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0011_income_time_alter_income_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
