# Generated by Django 5.1.2 on 2025-04-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0012_alter_income_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
