# Generated by Django 5.1.2 on 2025-04-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0014_expense_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='expense',
        ),
    ]
