# Generated by Django 5.1.2 on 2025-04-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0016_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatmentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patment_method', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
