# Generated by Django 5.1.2 on 2025-04-07 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0017_patmentmethod_delete_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('patment_method', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('desription', models.TextField(blank=True, default='', null=True)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True, null=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.category')),
                ('patment_method_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.patmentmethod')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.user')),
            ],
        ),
    ]
