# Generated by Django 5.1.2 on 2025-04-07 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0021_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='patment_method_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.patmentmethod'),
        ),
    ]
