# Generated by Django 5.1.2 on 2025-04-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0023_rename_desription_expense_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='patment_method_id',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='budget',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='PatmentMethod',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='income',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
