# Generated by Django 5.1.2 on 2025-04-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0025_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='patment_method',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='patment_method_id',
            new_name='payment_method_id',
        ),
        migrations.RenameField(
            model_name='patmentmethod',
            old_name='patment_method',
            new_name='payment_method',
        ),
    ]
