# Generated by Django 5.1.7 on 2025-04-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0026_rename_patment_method_expense_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatmentMethod',
            new_name='PaymentMethod',
        ),
    ]
