# Generated by Django 5.1.2 on 2025-04-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0027_rename_patmentmethod_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
