# Generated by Django 5.1.2 on 2025-04-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0028_income_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='payment_method_id',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='income',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='IncomeCategory',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
