# Generated by Django 5.1.2 on 2025-04-21 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0030_expensecategory_incomecategory_paymentmethod_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.incomecategory'),
        ),
    ]
