# Generated by Django 5.1.2 on 2025-04-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0031_alter_expense_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='payment_method_id',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='income',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='income',
            name='payment_method_id',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
