# Generated by Django 5.1.2 on 2025-04-23 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0032_remove_budget_category_id_remove_budget_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_category', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True, null=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.incomecategory')),
                ('payment_method_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.paymentmethod')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.user')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.user')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.expensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True, null=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.incomecategory')),
                ('payment_method_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.paymentmethod')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.user')),
            ],
        ),
    ]
