# Generated by Django 5.1.2 on 2025-04-25 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0036_userpaymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='payment_method_id',
        ),
        migrations.RemoveField(
            model_name='income',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='income',
            name='payment_method_id',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.incomecategory'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.userpaymentmethod'),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.incomecategory'),
        ),
        migrations.AlterField(
            model_name='income',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.userpaymentmethod'),
        ),
    ]
