# Generated by Django 5.1.2 on 2025-04-25 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0038_remove_income_category_remove_income_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.incomecategory')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.userpaymentmethod')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.user')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.incomecategory')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.userpaymentmethod')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.user')),
            ],
        ),
    ]
