# Generated by Django 5.1.2 on 2025-04-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0039_expense_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
