# Generated by Django 5.2.5 on 2025-09-14 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0041_expense_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userpaymentmethod',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='userpaymentmethod',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='IncomeCategory',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserPaymentMethod',
        ),
    ]
